<?php
/**
 * Message translations.
 * 
 * en-US
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	
	/**
	 * Default transaction notes
	 */
	'transaction_action_initial_credit' => 'Initial credit',
	'transaction_action_update_credit' => 'Adjusted by Admin',
	'transaction_action_place_bet' => 'Placed bet',
	'transaction_action_win_bet' => 'Won bet',
	'transaction_action_reevaluation_bet' => 'Bet reevaluated',
	'transaction_action_return_bet' => 'Bet returned',


	/**
	 * Complaint email
	 */
	'email_complaint_form_subject' => 'New complaint from user',


	/**
	 * Contact email
	 */
	'email_contact_form_subject' => 'New message from contact form',

];
