<?php
/**
 * Message translations.
 * 
 * en-US
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

	/**
	 * General
	 */
	'app_status_error_generic' => 'Background services are experiencing interruptions. Logging in is currently not possible. Please contact the system administrator.',

	
	/**
	 * Generic model validation
	 */
	'model_field_required' => 'This field is required.',
	'model_field_too_short' => 'Please enter at least {length} characters.',
	'model_field_email' => 'Please enter a valid email address.',
	'model_field_email_unique' => 'This email is already in use.',
	'model_field_password_short' => 'The password is too short. It must contain at least {length} characters.',
	'model_field_password_strength' => 'The password must contain at least one lowercase letter, one uppercase letter, and one number.',
	'model_field_password_verify_not_equal' => 'The confirmation password does not match.',

	/**
	 * Signup form
	 */
	'signup_form_agree_terms_required' => 'Your agreement is required for registration.',
	'signup_form_confirm_age_required' => 'Please confirm your age.',
	'model_field_nickname_unique' => 'This nickname is already in use.',


	/**
	 * Login form
	 */
	'login_form_email_or_password_incorrect' => 'The entered e-mail or password is incorrect.',
	'login_form_app_status_error' => 'Background services are experiencing interruptions. Logging in is currently not possible. Please contact the system administrator.',


	/**
	 * Contact form
	 */
	'contact_form_topic_required' => 'Please select a topic.',
	'contact_form_message_required' => 'Please enter a message.',

	/**
	 * Complaint form
	 */
	'complaint_form_message_required' => 'Please enter a message.',

	/**
	 * Bet form
	 */
	'bet_form_amount_required' => 'Please enter a bet amount.',
	'bet_form_amount_insufficient_funds' => 'You do not have enough Betcoins to place this bet.',
	'bet_form_amount_minimum' => 'The bet amount must be at least {min}.',
	'bet_form_amount_numeric' => 'The bet amount must be a number.',
	'bet_form_odd_id_required' => 'Please select a valid odd.',
	'bet_form_match_in_progress' => 'Cannot place bet. Match is currently in progress.',
	'bet_form_match_inactive' => 'Cannot place bet. Match is not available.',

];
