<?php
/**
 * Message translations.
 * 
 * en-US
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    /**
     * General
     */
    'select_default_prompt' => 'Select',
    'grid_filter_select_all' => 'All',
    'state_value_yes' => 'Yes',
    'state_value_no' => 'No',
    'update_button' => 'Edit',
    'delete_button' => 'Delete',
    'save_button' => 'Save',
    'send_button' => 'Send',
    'back_button' => 'Back',
	'app_status_error_generic' => 'Warning: Background services are experiencing interruptions. Logging in is currently not possible. Please contact the system administrator.',


    /**
     * Generic model validation
     */
	'model_field_required' => 'This field is required.',
	'model_field_too_short' => 'Please enter at least {length} characters.',
	'model_field_email' => 'Please enter a valid email address.',
	'model_field_email_unique' => 'This email is already in use.',
	'model_field_password_short' => 'The password is too short. It must contain at least {length} characters.',
	'model_field_password_strength' => 'The password must contain at least one lowercase letter, one uppercase letter, and one number.',
	'model_field_password_verify_not_equal' => 'The confirmation password does not match.',


    /**
     * Funds
     */
    'model_field_funds_amount_integer' => 'Please enter a whole number.',
    'model_field_funds_amount_minimum' => 'Minimum amount is {min}.',
    'model_field_funds_amount_maximum' => 'Maximum amount is {max}.',
    'model_field_funds_amount_zero' => 'Amount can not be zero.',
    'model_field_funds_result_balance_negative' => 'Invalid amount. The resulting balance cannot be negative.',
	
    
    /**
	 * Login form
	 */
	'login_form_email_or_password_incorrect' => 'The entered e-mail or password is incorrect.',


    /**
     * User Create form
     */
    'model_field_nickname_unique' => 'This nickname is already in use.',


    /**
     * User Update form
     */
    'user_update_account_success' => 'Account details updated successfully.',
    'user_update_balance_success' => 'Balance updated successfully.',
    'user_change_password_success' => 'Password changed successfully.',


    /**
     * Sport Match Result form
     */
    'sport_match_result_form_id_required' => 'Sport match result ID is required.',
    'sport_match_result_form_score_minimum' => 'Score must be at least {min}.',
    'sport_match_result_form_success' => 'Match results have been changed successfully.',


    /**
     * User
     */
    'user_list_title' => 'Users',
    'user_status_active' => 'Active',
    'user_status_inactive' => 'Inactive',
    'user_status_deleted' => 'Deleted',

    
    /**
     * Matches
     */
    'match_list_title' => 'Matches',

    /**
     * Categories
     */

    'categories_title' => 'Categories',
];
